apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../manifest/argocd/project/gitops-config/base
  - ../../../manifest/hashicorp-vault/base

resources:
  - gitops-manager.yaml
  - vault-namespace.yaml

  
  