apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-01-config
  namespace: argocd-01
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

