apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesJson6902:
  - target:
      kind: Application
      name: argocd-manager
      version: v1alpha1
      group: argoproj.io
    path: patch-slack-subscription.yaml
  
  - target:
      kind: Application
      name: argocd-manager
      version: v1alpha1
      group: argoproj.io
    path: patch-vault-plugin.yaml
