apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-01

bases:
  - ../../../manifest/argocd/argocd-notifications/overlays
  - ../base
  
resources:
  - notifications-secret.yaml